package com.quejas.diaco.entity;
// Generated 20/09/2021 12:21:51 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TblConsumidor generated by hbm2java
 */
@Entity
@Table(name="tbl_consumidor"
    ,catalog="diacobd"
)
public class TblConsumidor  implements java.io.Serializable {


     private int idConsumidor;
     private TblDepartamento tblDepartamento;
     private TblMunicipio tblMunicipio;
     private String genero;
     private String nacionalidad;
     private String tipoConsumidor;
     private Set<TblQueja> tblQuejas = new HashSet<TblQueja>(0);

    public TblConsumidor() {
    }

	
    public TblConsumidor(int idConsumidor, TblDepartamento tblDepartamento, TblMunicipio tblMunicipio) {
        this.idConsumidor = idConsumidor;
        this.tblDepartamento = tblDepartamento;
        this.tblMunicipio = tblMunicipio;
    }
    public TblConsumidor(int idConsumidor, TblDepartamento tblDepartamento, TblMunicipio tblMunicipio, String genero, String nacionalidad, String tipoConsumidor, Set<TblQueja> tblQuejas) {
       this.idConsumidor = idConsumidor;
       this.tblDepartamento = tblDepartamento;
       this.tblMunicipio = tblMunicipio;
       this.genero = genero;
       this.nacionalidad = nacionalidad;
       this.tipoConsumidor = tipoConsumidor;
       this.tblQuejas = tblQuejas;
    }
   
     @Id 

    
    @Column(name="id_consumidor", unique=true, nullable=false)
    public int getIdConsumidor() {
        return this.idConsumidor;
    }
    
    public void setIdConsumidor(int idConsumidor) {
        this.idConsumidor = idConsumidor;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_depto", nullable=false)
    public TblDepartamento getTblDepartamento() {
        return this.tblDepartamento;
    }
    
    public void setTblDepartamento(TblDepartamento tblDepartamento) {
        this.tblDepartamento = tblDepartamento;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_mun", nullable=false)
    public TblMunicipio getTblMunicipio() {
        return this.tblMunicipio;
    }
    
    public void setTblMunicipio(TblMunicipio tblMunicipio) {
        this.tblMunicipio = tblMunicipio;
    }

    
    @Column(name="genero", length=25)
    public String getGenero() {
        return this.genero;
    }
    
    public void setGenero(String genero) {
        this.genero = genero;
    }

    
    @Column(name="nacionalidad", length=25)
    public String getNacionalidad() {
        return this.nacionalidad;
    }
    
    public void setNacionalidad(String nacionalidad) {
        this.nacionalidad = nacionalidad;
    }

    
    @Column(name="tipo_consumidor", length=45)
    public String getTipoConsumidor() {
        return this.tipoConsumidor;
    }
    
    public void setTipoConsumidor(String tipoConsumidor) {
        this.tipoConsumidor = tipoConsumidor;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tblConsumidor")
    public Set<TblQueja> getTblQuejas() {
        return this.tblQuejas;
    }
    
    public void setTblQuejas(Set<TblQueja> tblQuejas) {
        this.tblQuejas = tblQuejas;
    }




}


