package com.quejas.diaco.entity;
// Generated 20/09/2021 12:21:51 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TblMunicipio generated by hbm2java
 */
@Entity
@Table(name="tbl_municipio"
    ,catalog="diacobd"
)
public class TblMunicipio  implements java.io.Serializable {


     private int idMun;
     private TblDepartamento tblDepartamento;
     private String nombre;
     private Set<TblQueja> tblQuejas = new HashSet<TblQueja>(0);
     private Set<TblConsumidor> tblConsumidors = new HashSet<TblConsumidor>(0);

    public TblMunicipio() {
    }

	
    public TblMunicipio(int idMun, TblDepartamento tblDepartamento, String nombre) {
        this.idMun = idMun;
        this.tblDepartamento = tblDepartamento;
        this.nombre = nombre;
    }
    public TblMunicipio(int idMun, TblDepartamento tblDepartamento, String nombre, Set<TblQueja> tblQuejas, Set<TblConsumidor> tblConsumidors) {
       this.idMun = idMun;
       this.tblDepartamento = tblDepartamento;
       this.nombre = nombre;
       this.tblQuejas = tblQuejas;
       this.tblConsumidors = tblConsumidors;
    }
   
     @Id 

    
    @Column(name="id_mun", unique=true, nullable=false)
    public int getIdMun() {
        return this.idMun;
    }
    
    public void setIdMun(int idMun) {
        this.idMun = idMun;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_depto", nullable=false)
    public TblDepartamento getTblDepartamento() {
        return this.tblDepartamento;
    }
    
    public void setTblDepartamento(TblDepartamento tblDepartamento) {
        this.tblDepartamento = tblDepartamento;
    }

    
    @Column(name="nombre", nullable=false, length=45)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tblMunicipio")
    public Set<TblQueja> getTblQuejas() {
        return this.tblQuejas;
    }
    
    public void setTblQuejas(Set<TblQueja> tblQuejas) {
        this.tblQuejas = tblQuejas;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tblMunicipio")
    public Set<TblConsumidor> getTblConsumidors() {
        return this.tblConsumidors;
    }
    
    public void setTblConsumidors(Set<TblConsumidor> tblConsumidors) {
        this.tblConsumidors = tblConsumidors;
    }




}


