package com.quejas.diaco.entity;
// Generated 20/09/2021 12:21:51 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TblQueja generated by hbm2java
 */
@Entity
@Table(name="tbl_queja"
    ,catalog="diacobd"
)
public class TblQueja  implements java.io.Serializable {


     private Integer idQueja;
     private TblConsumidor tblConsumidor;
     private TblDepartamento tblDepartamento;
     private TblMunicipio tblMunicipio;
     private TblSede tblSede;
     private String nombreNegocio;
     private String nitNegocio;
     private String direccion;
     private String noFactura;
     private Date fechaFactura;
     private Date fechaCreacion;
     private String solicitudQueja;
     private String telefono;
     private String correo;

    public TblQueja() {
    }

	
    public TblQueja(TblConsumidor tblConsumidor, TblDepartamento tblDepartamento, TblMunicipio tblMunicipio, TblSede tblSede) {
        this.tblConsumidor = tblConsumidor;
        this.tblDepartamento = tblDepartamento;
        this.tblMunicipio = tblMunicipio;
        this.tblSede = tblSede;
    }
    public TblQueja(TblConsumidor tblConsumidor, TblDepartamento tblDepartamento, TblMunicipio tblMunicipio, TblSede tblSede, String nombreNegocio, String nitNegocio, String direccion, String noFactura, Date fechaFactura, Date fechaCreacion, String solicitudQueja, String telefono, String correo) {
       this.tblConsumidor = tblConsumidor;
       this.tblDepartamento = tblDepartamento;
       this.tblMunicipio = tblMunicipio;
       this.tblSede = tblSede;
       this.nombreNegocio = nombreNegocio;
       this.nitNegocio = nitNegocio;
       this.direccion = direccion;
       this.noFactura = noFactura;
       this.fechaFactura = fechaFactura;
       this.fechaCreacion = fechaCreacion;
       this.solicitudQueja = solicitudQueja;
       this.telefono = telefono;
       this.correo = correo;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_queja", unique=true, nullable=false)
    public Integer getIdQueja() {
        return this.idQueja;
    }
    
    public void setIdQueja(Integer idQueja) {
        this.idQueja = idQueja;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_consumidor", nullable=false)
    public TblConsumidor getTblConsumidor() {
        return this.tblConsumidor;
    }
    
    public void setTblConsumidor(TblConsumidor tblConsumidor) {
        this.tblConsumidor = tblConsumidor;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_depto", nullable=false)
    public TblDepartamento getTblDepartamento() {
        return this.tblDepartamento;
    }
    
    public void setTblDepartamento(TblDepartamento tblDepartamento) {
        this.tblDepartamento = tblDepartamento;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_mun", nullable=false)
    public TblMunicipio getTblMunicipio() {
        return this.tblMunicipio;
    }
    
    public void setTblMunicipio(TblMunicipio tblMunicipio) {
        this.tblMunicipio = tblMunicipio;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_sede", nullable=false)
    public TblSede getTblSede() {
        return this.tblSede;
    }
    
    public void setTblSede(TblSede tblSede) {
        this.tblSede = tblSede;
    }

    
    @Column(name="nombre_negocio")
    public String getNombreNegocio() {
        return this.nombreNegocio;
    }
    
    public void setNombreNegocio(String nombreNegocio) {
        this.nombreNegocio = nombreNegocio;
    }

    
    @Column(name="nit_negocio", length=45)
    public String getNitNegocio() {
        return this.nitNegocio;
    }
    
    public void setNitNegocio(String nitNegocio) {
        this.nitNegocio = nitNegocio;
    }

    
    @Column(name="direccion")
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }

    
    @Column(name="no_factura")
    public String getNoFactura() {
        return this.noFactura;
    }
    
    public void setNoFactura(String noFactura) {
        this.noFactura = noFactura;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha_factura", length=10)
    public Date getFechaFactura() {
        return this.fechaFactura;
    }
    
    public void setFechaFactura(Date fechaFactura) {
        this.fechaFactura = fechaFactura;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fecha_creacion", length=19)
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }

    
    @Column(name="solicitud_queja")
    public String getSolicitudQueja() {
        return this.solicitudQueja;
    }
    
    public void setSolicitudQueja(String solicitudQueja) {
        this.solicitudQueja = solicitudQueja;
    }

    
    @Column(name="telefono", length=13)
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }

    
    @Column(name="correo")
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }




}


