package com.quejas.diaco.entity;
// Generated 20/09/2021 12:21:51 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TblSede generated by hbm2java
 */
@Entity
@Table(name="tbl_sede"
    ,catalog="diacobd"
)
public class TblSede  implements java.io.Serializable {


     private int idSede;
     private String nombreSede;
     private Set<TblQueja> tblQuejas = new HashSet<TblQueja>(0);

    public TblSede() {
    }

	
    public TblSede(int idSede) {
        this.idSede = idSede;
    }
    public TblSede(int idSede, String nombreSede, Set<TblQueja> tblQuejas) {
       this.idSede = idSede;
       this.nombreSede = nombreSede;
       this.tblQuejas = tblQuejas;
    }
   
     @Id 

    
    @Column(name="id_sede", unique=true, nullable=false)
    public int getIdSede() {
        return this.idSede;
    }
    
    public void setIdSede(int idSede) {
        this.idSede = idSede;
    }

    
    @Column(name="nombre_sede", length=45)
    public String getNombreSede() {
        return this.nombreSede;
    }
    
    public void setNombreSede(String nombreSede) {
        this.nombreSede = nombreSede;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tblSede")
    public Set<TblQueja> getTblQuejas() {
        return this.tblQuejas;
    }
    
    public void setTblQuejas(Set<TblQueja> tblQuejas) {
        this.tblQuejas = tblQuejas;
    }




}


