package com.quejas.diaco.entity;
// Generated 19/09/2021 05:28:55 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Test generated by hbm2java
 */
@Entity
@Table(name="test"
    ,catalog="diacobd"
)
public class Test  implements java.io.Serializable {


     private Integer id;
     private String nombre;
     private String queja;
     private String factura;

    public Test() {
    }

    public Test(String nombre, String queja, String factura) {
       this.nombre = nombre;
       this.queja = queja;
       this.factura = factura;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="nombre", length=45)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="queja", length=60)
    public String getQueja() {
        return this.queja;
    }
    
    public void setQueja(String queja) {
        this.queja = queja;
    }

    
    @Column(name="factura", length=60)
    public String getFactura() {
        return this.factura;
    }
    
    public void setFactura(String factura) {
        this.factura = factura;
    }




}


